/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: ibotpl (https://sketchfab.com/ibotpl)
license: SKETCHFAB Standard (https://sketchfab.com/licenses)
source: https://sketchfab.com/3d-models/cans-with-droplets-61e818dd2eff4da9b98857c631c30b06
title: Cans with Droplets
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Model({ scroll }, ...props) {
  const group = useRef();
  const ref = useRef();

  const { nodes, materials } = useGLTF("/cans_with_droplets/scene.gltf");

  useFrame(({ clock }) => {
    group.current.rotation.y =
      scroll.current == 1
        ? group.current.rotation.y + 0.001
        : scroll.current + 10;

    group.current.up.y = 0;

    group.current.rotation.z =
      scroll.current == 1 ? 0 : clock.getElapsedTime() / 2;

    group.current.rotation.x =
      scroll.current == 1 ? 0 : clock.getElapsedTime() / 2;
  });
  console.log(materials);
  console.log(nodes);
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[100, 100, 100]}
          ></group>
          <group
            position={[-0.05, 6.29, -7.45]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 4]}
            scale={[93.61, 94.15, 87.79]}
          >
            <mesh
              geometry={nodes["330ml_drops_water_0"].geometry}
              material={nodes["330ml_drops_water_0"].material}
            />
            <mesh
              geometry={nodes["330ml_drops_water_0_1"].geometry}
              material={nodes["330ml_drops_water_0_1"].material}
            />
          </group>
          <group
            rotation={[-Math.PI / 2, 0, -Math.PI / 4]}
            scale={[71.4, 71.4, 71.4]}
          ></group>
          <group
            position={[0, 0, -7.53]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 4]}
            scale={[93.61, 94.15, 87.79]}
          >
            <mesh
              geometry={nodes["330ml_can_body_0"].geometry}
              material={nodes["330ml_can_body_0"].material}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/cans_with_droplets/scene.gltf");
